import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import yudhaImage from "../public/headshot.jpg";
import { useState } from "react";
import SocialMediaButtons from "./socialMediaButtons";
import NavigationBar from "./navigationBar";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const toggleDarkMode = () => {
    console.log("this was clicked");
    setDarkMode(!darkMode);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Yudha Firdaus Portfolio</title>
        <meta name="description" content="Generated by cre"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>

      <main className="bg-white dark:bg-gray-900 px-10 md:px-20 lg:px-40 ">
        <section className=" min-h-screen">
          <NavigationBar toggleDarkMode={toggleDarkMode} />

          <div className="text-center px-10 pb-10">
            <h2 className="sm:text-5xl text-4xl py-2 text-teal-600 font-medium md:text-6xl">
              Yudha Firdaus
            </h2>
            <h3 className="sm:text-2xl text-xl py-2 md:text-3xl dark:text-white">
              Frontend Developer.
            </h3>
            <p className="sm:text-md text-sm py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto">
              Hey there! I'm a computer science student who loves coding and
              crafting beautiful user experiences. Let's bring your projects to
              life together!
            </p>
          </div>

          <SocialMediaButtons />

          {/* mx auto will center it */}
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full sm:w-80 w-40 sm:h-80 h-40 mt-20 overflow-hidden">
            <Image src={yudhaImage} className="object-cover" />
          </div>

          <div className="h-20"></div>
        </section>
      </main>
    </div>
  );
}
