import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import yudhaImage from "../public/headshot.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Yudha Firdaus Portfolio</title>
        <meta name="description" content="Generated by cre"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>

      <main className="bg-white dark:bg-gray-900 px-10 md:px-20 lg:px-40 ">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="sm:text-xl text-sm font-burtons dark:text-white">
              developedbyYudha
            </h1>
            <BsFillMoonStarsFill
              onClick={() => {
                setDarkMode(!darkMode);
              }}
              className="cursor-pointer sm:text-xl text-lg dark:text-white"
            />
          </nav>

          <div className="text-center p-10 ">
            <h2 className="sm:text-5xl text-4xl py-2 text-teal-600 font-medium md:text-6xl">
              Yudha Firdaus
            </h2>
            <h3 className="sm:text-2xl text-xl py-2 md:text-3xl dark:text-white">
              Frontend Developer.
            </h3>
            <p className="sm:text-md text-sm py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto">
              Hey there! I'm a computer science student who loves coding and
              crafting beautiful user experiences. Let's bring your projects to
              life together!
            </p>
          </div>

          <div className="sm:text-5xl text-4xl flex justify-center gap-16 py-3 text-gray-600  dark:text-gray-400">
            <AiFillLinkedin className="cursor-pointer" />
            <AiFillGithub className="cursor-pointer" />
          </div>

          {/* mx auto will center it */}
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full sm:w-80 w-40 sm:h-80 h-40 my-10 overflow-hidden">
            <Image src={yudhaImage} className="object-cover" />
          </div>
        </section>
      </main>
    </div>
  );
}
